runtime: python39
instance_class: F4_1G
env_variables:
  OPENAI_API_KEY: 'sk-key'
  PYTHONPATH: '$PYTHONPATH:~/bot_os'
  GOOGLE_APPLICATION_CREDENTIALS: '.secrets/gcp.json'
  SLACK_APP_SIGNING_SECRET: 6fbb5139eef6d320ffbb386ea3738536
  SLACK_APP_TOKEN: xoxb-6550650260448-6711150401381-4OVOCDHDRMdHUAdYyphsXPaa
  SLACK_CHANEL: elsa_test_jl
  SLACK_BOT_USERID: 'U06LX4EBTB7'
