name: Build Source Distribution

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Source Distribution
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: '1.0.40'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        python -m build --sdist

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: genesis_bots-${{ env.PACKAGE_VERSION }}
        path: dist/
        if-no-files-found: error
        compression-level: 0
        retention-days: 5

    - name: List built files
      run: |
        ls -R dist/