name: Build Cython Package

env:
  COMPILE_CYTHON: true

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel cython numpy build
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        fi
      shell: bash

    - name: Build package
      env:
        PACKAGE_VERSION: '1.0.36'
        COMPILE_CYTHON: true
      run: |
        # Run build.py from the project root
        python build/build.py --version ${PACKAGE_VERSION}

    - name: Test installation
      run: |
        pip install build/dist/*.whl
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-ubuntu-latest-py3.12
        path: build/dist/
        retention-days: 5

    - name: List compiled files
      run: |
        ls -R build/dist/
      shell: bash