name: Build Source Distribution

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type (patch/minor/major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    name: Build Source Distribution
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Bump version
      run: |
        pip install bump2version
        bump2version ${{ github.event.inputs.bump_type }}
        echo "NEW_VERSION=$(grep 'current_version' .bumpversion.cfg | cut -d' ' -f3)" >> $GITHUB_ENV

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build --sdist

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-sdist-py3.12
        path: dist/
        retention-days: 5

    - name: List built files
      run: ls -R dist/

    - name: Push changes
      run: |
        git push
        git push --tags