name: Docker Build and Push

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        required: true
        default: '1.0.40'
      should_push:
        description: 'Push to Docker Hub'
        type: boolean
        default: false

env:
  DEFAULT_VERSION: '1.0.40'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set environment variables
        run: |
          echo "DOCKER_IMAGE_NAME=genesiscomputing/genesis_app" >> $GITHUB_ENV
          echo "VERSION=${{ github.event.inputs.version || env.DEFAULT_VERSION }}" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        if: ${{ github.event.inputs.should_push == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event.inputs.should_push == 'true' }}
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}
          outputs: type=docker,dest=/tmp/docker-image.tar
          
      - name: Upload Docker image as artifact
        if: ${{ github.event.inputs.should_push != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/docker-image.tar
          retention-days: 1 