name: Run Reg Test

on:
  push:
    branches:
      - main  # Triggers on push to the main branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-snowflake-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the version of Python you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Snowflake Python script
      env:
        SNOWFLAKE_USER_OVERRIDE: ${{ secrets.SNOWFLAKE_USER_OVERRIDE }}
        SNOWFLAKE_ACCOUNT_OVERRIDE: ${{ secrets.SNOWFLAKE_ACCOUNT_OVERRIDE }}
        SNOWFLAKE_WAREHOUSE_OVERRIDE: ${{ secrets.SNOWFLAKE_WAREHOUSE_OVERRIDE }}
        SNOWFLAKE_DATABASE_OVERRIDE: ${{ secrets.SNOWFLAKE_DATABASE_OVERRIDE }}
        SNOWFLAKE_ROLE_OVERRIDE: ${{ secrets.SNOWFLAKE_ROLE_OVERRIDE }}
        SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
        PRIVATE_KEY_PASSPHRASE: ${{ secrets.PRIVATE_KEY_PASSPHRASE }} # Only if you used a passphrase
      run: |
        python tests/hello_world_regtest_01.py
