name: Run Unittest Tests

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-snowflake-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      # Cache Python dependencies (including SnowCLI)
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Set up Python and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements.txt
          pip install pytest

      - name: Add user-level bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH


      - name: Run Unittests
        env:
          SNOWFLAKE_METADATA: FALSE
          SPCS_MODE: FALSE

        run: |
          pytest -v
