name: Run Unittest Tests

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-snowflake-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Cache Python dependencies
        uses: actions/cache@v3
        id:   cache-venv
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pytest
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Add user-level bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run Unittests
        env:
          SNOWFLAKE_METADATA: FALSE
          SPCS_MODE: FALSE

        run: |
          pytest -v
